name: Custom Bandit Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r . -f json -o bandit-report-${{ matrix.python-version }}.json

    - name: Upload Bandit Report as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report-${{ matrix.python-version }}
        path: bandit-report-${{ matrix.python-version }}.json
