on: [push]

jobs:
  salus_scan_job:
    runs-on: ubuntu-latest
    name: Salus Security Scan Example
    steps:
    - uses: actions/checkout@v1
    - name: Salus Security Scan (SAST/Dependency Check)
      id: salus_scan
      uses: federacy/scan-action@0.1.4
      with:
          enforced_scanners: "none"